src/objects/afl_Article_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Article_Number__c</fullName>
        <label>Article Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Version__c</fullName>
        <label>Article Version</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>afl_Article_Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Feedback_Source__c</fullName>
        <label>Feedback Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Communities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Feedback_Status__c</fullName>
        <label>Feedback Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Knowledge_kav_article_Id__c</fullName>
        <description>Holds the value of the field KnowledgeArticleId from the Knowledge__kav object. Used for register/retrieve the vote on the Vote object for a Knowledge Article</description>
        <label>Knowledge kav article Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Article Feedback</label>
    <nameField>
        <label>Article Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Article Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/afl_Article_Feedback__c/fields/Feedback_Reason__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Reason__c</fullName>
    <description>Reason provided for feedback</description>
    <label>Feedback Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/afl_RelatedFeedbackCtrl.cls
/**
* @author Altimetrik
* @description Front Controller for Article Feedback Related List
**/
public with sharing class afl_RelatedFeedbackCtrl {
    
    /*
    * Retrieves all the Feedback left in the Knowledge Article
    * @param kavId
    * @return afl_LightningResponse
    */
    @AuraEnabled(cacheable=true)
	public static afl_LightningResponse getRelatedFeedback(String kavId) {
		try {
			// Check FLS
			afl_ArticleFeedbackSecurityHandler.canAccess(Schema.SObjectType.afl_Article_Feedback__c.getSobjectType());
			
            String knowledgeObject = afl_ArticleFeedbackSecurityHandler.knowledgeObject;
            String query = 'SELECT VersionNumber, ArticleNumber, PublishStatus, KnowledgeArticleId FROM ' + knowledgeObject + ' WHERE Id = \'' + kavId + '\' WITH SECURITY_ENFORCED LIMIT 1';
            List<SObject> sObjList = Database.query(query);

            List<afl_Article_Feedback__c> afList = new List<afl_Article_Feedback__c>();

            if (!sObjList.isEmpty()) {
				SObject sObj = sObjList[0];
				String masterVersionId = (String) sObj.get('KnowledgeArticleId');
				Integer versionNumber = (Integer) sObj.get('VersionNumber');
				String articleNumber = (String) sObj.get('ArticleNumber');

                afList = [
                    SELECT Id, Name, Feedback_Source__c, Feedback_Status__c, Feedback_Reason__c, Assigned_To__r.Name
                    FROM afl_Article_Feedback__c 
                    WHERE Knowledge_kav_article_Id__c =:masterVersionId 
                    AND Article_Number__c =:articleNumber
                    AND Article_Version__c =:versionNumber
                    WITH SECURITY_ENFORCED
                    ORDER BY CreatedDate DESC
                ];
            }
			afl_LightningResponse response = new afl_LightningResponse();
            response.jsonResponse = JSON.serialize(afList);
            return response;
        } catch (Exception e) {
			return new afl_LightningResponse(e);
		}
    }
}