src/objects/afl_Knowledge_feedback__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for Knowledge Feedback Tracking</description>
    <fields>
        <fullName>Hashtag__c</fullName>
        <defaultValue>&quot;#ArticleFeedback&quot;</defaultValue>
        <description>Hashtag is used to create an Article Feedback object when it is present in a Chatter feed for an Article.</description>
        <inlineHelpText>Type prefixed with the hash character (#).</inlineHelpText>
        <label>Hashtag</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Knowledge feedback</label>
</CustomObject>

src/classes/afl_ArticleFeedbackConfigCtrl_Test.cls
/**
* @author Altimetrik
* @description
*    started on 07/12/2018
*    Test class for the afl_ArticleFeedbackConfigCtrl class
**/
@isTest
public class afl_ArticleFeedbackConfigCtrl_Test {
	static testMethod void test_config() {
		afl_Knowledge_Feedback__c setting = new afl_Knowledge_Feedback__c();
		setting.Hashtag__c = '#TestHashtag';
		INSERT setting;
		
		System.Test.startTest();
		System.assertNotEquals(null,setting);
		afl_ArticleFeedbackConfigCtrl ctr = new afl_ArticleFeedbackConfigCtrl();
		ctr.edit();
		ctr.csObj.HashTag__c ='#MyTestHashtag';
		ctr.save();
		setting = afl_Knowledge_Feedback__c.getOrgDefaults();
		system.assertEquals('#MyTestHashtag',setting.Hashtag__c);
		ctr.cancel();
		System.Test.stopTest();
	}
}