src/objects/afl_Article_Feedback__c.object
<CustomObject>
    <label>Article Feedback</label>
    <nameField>
        <label>Article Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Article Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/afl_Knowledge_feedback__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for Knowledge Feedback Tracking</description>
    <fields>
        <fullName>Hashtag__c</fullName>
        <defaultValue>&quot;#ArticleFeedback&quot;</defaultValue>
        <description>Hashtag is used to create an Article Feedback object when it is present in a Chatter feed for an Article.</description>
        <inlineHelpText>Type prefixed with the hash character (#).</inlineHelpText>
        <label>Hashtag</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Knowledge feedback</label>
</CustomObject>

04t5w000004ckajAAA/objects/Article_Feedback_Values__c.object
<CustomObject>
    <description>Object that stores article feedback configuration data.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Negative__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Negative</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Positive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Positive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Article Feedback Values (Deprecated)</label>
    <language>en_US</language>
    <nameField>
        <label>Article Feedback Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Article Feedback Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/afl_ArticleFeedbackLgnConfigCtrl.cls
/**
* @author Altimetrik
* @description
*    started on 08/06/2018
*    Front Controller for Article Feedback project setup page
**/
public with sharing class afl_ArticleFeedbackLgnConfigCtrl {
	public String currentPrefix {get; private set;}

	public afl_ArticleFeedbackLgnConfigCtrl() {
		getCurrentNamespace();
	}

	/*
    * @description
    *    Logic to resolve namespace prefix
    * @return
    *    String with namespace prefix
    */
    private void getCurrentNamespace() {
		String prefix = afl_ArticleFeedbackLgnConfigCtrl.class.getName().substringBefore('afl_ArticleFeedbackLgnConfigCtrl');
        prefix = String.isBlank(prefix) ? 'c' : prefix.substringBefore('.');
        currentPrefix = prefix;
    }

	/*
	* @description
	*	Method that gets the data from the afl_Knowledge_feedback__c object
	* @params
	*	None
	* @return
	*	JSON - values
	*/
	@auraEnabled
	public static afl_LightningResponse getInitialData() {
		// afl_ArticleFeedbackSecurityHandler.canAccess(Article_Feedback_Configuration__c.SObjectType);

		afl_LightningResponse response = new afl_LightningResponse();
		Map<String,String> result = new Map<String, String>();
		afl_Knowledge_feedback__c af = afl_Knowledge_feedback__c.getOrgDefaults();
		try {
			if (String.isNotEmpty(af.Hashtag__c)) {
				result.put('hashtag', af.Hashtag__c);
			}

			// Retrieve config record
			

			response.jsonResponse = JSON.serialize(result);
		} catch(Exception e) {
			response = new afl_LightningResponse(e);
		}

		return response;
	}

	/*
	* @description
	*	Method that adds a picklist value to Article_Feedback_Values__c 
	* @params
	*	String with picklist value, Boolean with positive, Boolean with negative 
	* @return
	*	None
	*/
	@auraEnabled
	public static afl_LightningResponse addPicklistValue(String value, String type) {
	// public static afl_LightningResponse addPicklistValue(String value) {
		// Check FLS
		afl_ArticleFeedbackSecurityHandler.canAccess(Article_Feedback_Values__c.SObjectType);
		afl_ArticleFeedbackSecurityHandler.canCreate(Article_Feedback_Values__c.SObjectType);

		afl_LightningResponse response = new afl_LightningResponse();
		Map<String,String> result = new Map<String,String>();
		// List<Article_Feedback_Values__c> newValues = new List<Article_Feedback_Values__c>();

		// if (type == 'bothOption') {
		// 	newValues.add(createNewFeedbackValue(value, true, false));
		// 	newValues.add(createNewFeedbackValue(value, false, true));
		// } else if (type == 'positiveOption') {
		// 	newValues.add(createNewFeedbackValue(value, true, false));
		// } else {
		// 	newValues.add(createNewFeedbackValue(value, false, true));
		// }

		// try {
		// 	INSERT newValues;
		// 	result.put('status', 'SUCCESS');
		// } catch(Exception e) {
		// 	response = new afl_LightningResponse(e);
		// 	result.put('status', 'FAILED');
		// 	System.debug(e);
		// }
		result.put('status', 'SUCCESS');
		response.jsonResponse = JSON.serialize(result);

		return response;
	}
	
	/*
	* @description
	*	Method that creates a new instance of Article_Feedback_Values__c
	* @params
	*	String with picklist value, Boolean with positive value, Boolean with negative value
	* @return
	*	None
	*/
	public static Article_Feedback_Values__c createNewFeedbackValue(String value, Boolean positive, Boolean negative) {
		Article_Feedback_Values__c newValue = new Article_Feedback_Values__c(
			Value__c = value, 
			Positive__c = positive,
			Negative__c = negative,
			Active__c = false,
			Order__c = 0
		);
	
		return newValue;
	}

	/*
	* @description
	*	Method that updates the Hashtag value of the afl_Knowledge_feedback__c object
	* @params
	*	None
	* @return
	*	None
	*/
	@auraEnabled
	public static afl_LightningResponse updateHashtagValue(String value) {
		// Check FLS
		afl_ArticleFeedbackSecurityHandler.canCreate(afl_Article_Feedback__c.SObjectType);
		afl_ArticleFeedbackSecurityHandler.canUpdate(afl_Article_Feedback__c.SObjectType);

		afl_LightningResponse response = new afl_LightningResponse();
		Map<String,String> result = new Map<String,String>();
		afl_Knowledge_feedback__c af = afl_Knowledge_feedback__c.getOrgDefaults();
		try {
			if (String.isNotEmpty(value) && value != null) {
				af.Hashtag__c = value;
				UPSERT af;
				result.put('status', 'SUCCESS');
			}
		} catch(Exception e) {
			response = new afl_LightningResponse(e);
			result.put('status', 'FAILED');
		}
		response.jsonResponse = JSON.serialize(result);

		return response;
	}
}