src/objects/afl_Knowledge_feedback__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for Knowledge Feedback Tracking</description>
    <fields>
        <fullName>Hashtag__c</fullName>
        <defaultValue>&quot;#ArticleFeedback&quot;</defaultValue>
        <description>Hashtag is used to create an Article Feedback object when it is present in a Chatter feed for an Article.</description>
        <inlineHelpText>Type prefixed with the hash character (#).</inlineHelpText>
        <label>Hashtag</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Knowledge feedback</label>
</CustomObject>

src/classes/afl_TriggerHandler_Test.cls
/**
* @author Altimetrik
* @description
*    started on 02/04/2019
*    Test class for afl_TriggerHandler
**/
@isTest
private with sharing class afl_TriggerHandler_Test {
	static testMethod void testHandleTriggerInsertion_FeedItem() {
		Test.startTest();
		// afl_TriggerHandler.handleTriggerInsertion('FeedItem');
		Test.stopTest();

		// afl_Knowledge_feedback__c kf = afl_Knowledge_feedback__c.getOrgDefaults();

		// System.assertEquals(kf.Hashtag__c, '#ArticleFeedback', 'Hashtag should be "#ArticleFeedback"');
	}
}