src/objects/afl_Article_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Article_Number__c</fullName>
        <label>Article Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Title__c</fullName>
        <label>Article Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Version__c</fullName>
        <label>Article Version</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Feedback_Status__c</fullName>
        <label>Feedback Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Internal_Notes__c</fullName>
        <label>Internal Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Article Feedback</label>
    <nameField>
        <label>Article Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Article Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/afl_ArticleFeedbackRelatedCtrl_Test.cls
/**
 * @author Altimetrik
 * @description
 *    started on 07/05/2018
 *    Test class for the Article Feedback Related Controller class
 **/
@isTest
private class afl_ArticleFeedbackRelatedCtrl_Test {

	static testMethod void testTrigger() {

		// creates dummy Article Feedback objects
		afl_Article_Feedback__c afeedback = new afl_Article_Feedback__c();
        afeedback.Feedback_Status__c = 'New';
        afeedback.Article_Title__c = 'Test Article Title';
        afeedback.Article_Number__c = '00001';
        afeedback.Article_Type__c = 'Test Article Type';
        afeedback.Article_Version__c = 1;
        afeedback.Internal_Notes__c = 'Test notes 1';

        afl_Article_Feedback__c afeedback2 = new afl_Article_Feedback__c();
        afeedback2.Feedback_Status__c = 'New';
        afeedback2.Article_Title__c = 'Test Article Title';
        afeedback2.Article_Number__c = '00001';
        afeedback2.Article_Type__c = 'Test Article Type';
        afeedback2.Article_Version__c = 1;
        afeedback2.Internal_Notes__c = 'Test notes 2';

		insert afeedback;
        insert afeedback2;

        PageReference pageRef = Page.afl_ArticleFeedbackPage;

    	System.Test.startTest();
        	Test.setCurrentPage(pageRef);
            ApexPages.CurrentPage().getparameters().put('id', afeedback.id);
            ApexPages.StandardController sc = new ApexPages.standardController(afeedback);
            afl_ArticleFeedbackRelatedCtrl afsc = new afl_ArticleFeedbackRelatedCtrl(sc);
            System.assertNotEquals(afsc.records,null);
        System.Test.stopTest();
	}
}