src/objects/afl_Article_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Knowledge_Article_Version_Id__c</fullName>
        <inlineHelpText>Id from the corresponding KnowledgeArticleVersion</inlineHelpText>
        <label>Knowledge Article Version Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unlike_Reason__c</fullName>
        <label>Feedback Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Enhancement suggestion</fullName>
                </value>
                <value>
                    <fullName>Information inaccurate</fullName>
                </value>
                <value>
                    <fullName>Link broken</fullName>
                </value>
                <value>
                    <fullName>Need to archive</fullName>
                </value>
                <value>
                    <fullName>Outdated  (needs update)</fullName>
                </value>
                <value>
                    <fullName>Positive feedback</fullName>
                </value>
                <value>
                    <fullName>Poorly Written (not clear)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Does not Work</fullName>
                    <isActive>false</isActive>
                    <label>Does not Work</label>
                </value>
                <value>
                    <fullName>Outdated</fullName>
                    <isActive>false</isActive>
                    <label>Outdated</label>
                </value>
                <value>
                    <fullName>Poorly Written</fullName>
                    <isActive>false</isActive>
                    <label>Poorly Written</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Article Feedback</label>
    <nameField>
        <label>Article Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Article Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/afl_ArticleThumbVoteCtrlTest.cls
/**
 * @author Altimetrik
 * @description
 *    started on 11/28/2018
 *    Test class for the afl_ArticleThumbVoteCtrl class
 **/

@isTest
public class afl_ArticleThumbVoteCtrlTest {

	static testMethod void upsertThumbArticleVoteTest() {
		sObject knowledgeObject = afl_TestDataFactory.createKnowledgeArticle();
		Test.startTest();
		afl_LightningResponse response = afl_ArticleThumbVoteCtrl.upsertThumbArticleVote(knowledgeObject.Id, '', 'Test Description', true, false);
		Test.stopTest();
		afl_Article_Feedback__c[] afl = [SELECT Name FROM afl_Article_Feedback__c WHERE Knowledge_Article_Version_Id__c =: knowledgeObject.Id LIMIT 1];
		System.assert(!afl.isEmpty());
		System.assertEquals(1, afl.size());
	}

	static testMethod void getPickListValuesIntoListTest() {
		Test.startTest();
		afl_LightningResponse response = afl_ArticleThumbVoteCtrl.getPickListValuesIntoList();
		Map<String, Object> mResult = (Map<String, Object>)JSON.deserializeUntyped(response.jsonResponse);
		List<Object> pickListValuesList = (List<Object>)JSON.deserializeUntyped((String)mResult.get('result'));
		Test.stopTest();
		Schema.DescribeFieldResult fieldResult = afl_Article_Feedback__c.Unlike_Reason__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		System.assert(!pickListValuesList.isEmpty());
		System.assertEquals(ple.size(), pickListValuesList.size());

	}

	static testMethod void getVoteTest() {
		sObject knowledgeObject = afl_TestDataFactory.createKnowledgeArticle();
		String kavId = (String)knowledgeObject.get('Id');

		Test.startTest();
		afl_LightningResponse response = afl_ArticleThumbVoteCtrl.getVote(kavId);
		Map<String, Object> mResult = (Map<String, Object>)JSON.deserializeUntyped(response.jsonResponse);
		// Object value = (Object)JSON.deserialize(mResult.get('vote'), Boolean.class);
		Test.stopTest();
		System.assertEquals('true', mResult.get('vote'));

	}

}