src/objects/afl_Article_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Article_Title__c</fullName>
        <label>Article Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feedback__c</fullName>
        <label>Feedback from Article Feed</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originated_From_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True if the Article Feedback originated from the trigger</description>
        <label>Originated From Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Article Feedback</label>
    <nameField>
        <label>Article Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Article Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/afl_TriggerHandler_Test.cls
/**
* @author Altimetrik
* @description
*    started on 02/04/2019
*    Test class for afl_TriggerHandler
**/
@isTest
private with sharing class afl_TriggerHandler_Test {
	static testMethod void testHandleTriggerInsertion_FeedItem() {
		// Create knowledge article
		SObject article = afl_TestDataFactory.createKnowledgeArticle();

		Map<String,Schema.SOBjectType> gd = Schema.getGlobalDescribe();
		List<String> kavNames = new List<String>();

		for (String s : gd.keySet()) {
			if (s.contains('__ka')) {
					if (!s.contains('__kav')) {
					kavNames.add(s);
				}
			}
        }

		String objType = kavNames.get(0);

		String query = 'SELECT Id FROM ' + objType + ' LIMIT 1';
		SObject kavObj = Database.query(query);

		Test.startTest();
		FeedItem f = new FeedItem(
			Body = '#ArticleFeedback test',
			ParentId = (Id) kavObj.get('Id'),
			Type = 'TextPost'
		);

		INSERT f;
		Test.stopTest();

		afl_Article_Feedback__c feedback = [
			SELECT Article_Title__c, Feedback__c, Language__c, Originated_From_Trigger__c
			FROM afl_Article_Feedback__c
			LIMIT 1
		];

		System.assertEquals('#ArticleFeedback test', feedback.Feedback__c, 'The feedback should contain the Body of the FeedItem inserted');
		System.assert(feedback.Article_Title__c.contains('testTitle'), 'The title should contain "testTitle"');
		System.assert(feedback.Originated_From_Trigger__c, 'The feedback was created from the trigger so the flag should be true');
	}

	static testMethod void testHandleTriggerInsertion_FeedComment() {
		// Create knowledge article
		SObject article = afl_TestDataFactory.createKnowledgeArticle();

		Map<String,Schema.SOBjectType> gd = Schema.getGlobalDescribe();
		List<String> kavNames = new List<String>();

		for (String s : gd.keySet()) {
			if (s.contains('__ka')) {
					if (!s.contains('__kav')) {
					kavNames.add(s);
				}
			}
        }

		String objType = kavNames.get(0);

		String query = 'SELECT Id FROM ' + objType + ' LIMIT 1';
		SObject kavObj = Database.query(query);

		Test.startTest();
		FeedItem f1 = new FeedItem(
			Body = '#ArticleFeedback test',
			ParentId = (Id) kavObj.get('Id'),
			Type = 'TextPost'
		);

		INSERT f1;

		FeedComment f2 = new FeedComment(
			CommentBody = '#ArticleFeedback test',
			FeedItemId = f1.Id,
			CommentType = 'TextComment'
		);

		INSERT f2;
		Test.stopTest();

		afl_Article_Feedback__c feedback = [
			SELECT Article_Title__c, Feedback__c, Language__c, Originated_From_Trigger__c
			FROM afl_Article_Feedback__c
			ORDER BY CreatedDate DESC
			LIMIT 1
		];

		System.assertEquals('#ArticleFeedback test', feedback.Feedback__c, 'The feedback should contain the Body of the FeedComment inserted');
		System.assert(feedback.Article_Title__c.contains('testTitle'), 'The title should contain "testTitle"');
		System.assert(feedback.Originated_From_Trigger__c, 'The feedback was created from the trigger so the flag should be true');
	}
}