src/objects/afl_Knowledge_feedback__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for Knowledge Feedback Tracking</description>
    <fields>
        <fullName>Hashtag__c</fullName>
        <defaultValue>&quot;#ArticleFeedback&quot;</defaultValue>
        <description>Hashtag is used to create an Article Feedback object when it is present in a Chatter feed for an Article.</description>
        <inlineHelpText>Type prefixed with the hash character (#).</inlineHelpText>
        <label>Hashtag</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Knowledge feedback</label>
</CustomObject>

04t5w000004ckajAAA/objects/Article_Feedback_Values__c.object
<CustomObject>
    <description>Object that stores article feedback configuration data.</description>
    <fields>
        <fullName>Negative__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Negative</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderNegative__c</fullName>
        <label>OrderNegative</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrderPositive__c</fullName>
        <label>OrderPositive</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Positive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Positive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Article Feedback Values (Deprecated)</label>
    <language>en_US</language>
    <nameField>
        <label>Article Feedback Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Article Feedback Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/afl_TestDataFactory.cls
/**
 * @author Altimetrik
 * @description
 *    started on 07/10/2018
 *    Data Factory Class that creates or updates information to be used in test classes
 **/
@isTest
public class afl_TestDataFactory {
	/*
	* @description
	*	Creates a Knowledge Article object for testing purposes
	* @params
	*	None
	* @return
	*	SObject - Knowledge Article
	*/
	public static SObject createKnowledgeArticle() {
		// Creates Custom Article type
		Map<String,Schema.SOBjectType> gd = Schema.getGlobalDescribe();
		List<String> kavNames = new List<String>();

		for (String s : gd.keySet()) {
			if (s.contains('__kav')) {
				kavNames.add(s);
			}
        }

        String objType = kavNames.get(0);
	    SObject kavObj;
		afl_ArticleFeedbackSecurityHandler.canAccess(KnowledgeArticleVersion.SObjectType);
	    kavObj = Schema.getGlobalDescribe().get(objType).newSObject();
		afl_ArticleFeedbackSecurityHandler.canAccess(Schema.getGlobalDescribe().get(objType));
		kavObj.put('Title', 'testTitle' + String.valueOf(Crypto.getRandomInteger()));
	    kavObj.put('UrlName', 'testUrlName' + String.valueOf(Crypto.getRandomInteger()));
	    kavObj.put('Summary', 'testSummary');
	    kavObj.put('Language', afl_ArticleFeedbackSecurityHandler.getValidLanguagePicklistValue(objType));
		List<RecordType> allRecordTypes = afl_ArticleFeedbackSecurityHandler.allRecordTypes;
		if (allRecordTypes != null && allRecordTypes.size() > 0){
			kavObj.put('RecordTypeId', allRecordTypes[0].Id);
		}
	    INSERT kavObj;

		return kavObj;
	}

	/*
	* @description
	*	Creates the hashtag for testing purposes
	* @params
	*	String - hashtag name
	* @return
	*	none
	*/
	public static void createHashtagCustomSetting(String hashtag) {
		// Creates a Custom Setting at the organization level
		afl_Knowledge_Feedback__c setting= new afl_Knowledge_Feedback__c();
		setting.Hashtag__c = hashtag;
		INSERT setting;
	}

	/*
	* @description
	*	Creates a given User
	* @params
	*	String profile name
	* @return
	*	User
	*/
	public static User createUser(Boolean isAdmin) {
		// Create user for test
		Profile prof = [
			SELECT Id 
			FROM Profile 
			WHERE UserType = 'Standard' 
			AND PermissionsCustomizeApplication =: isAdmin 
			AND PermissionsModifyAllData =: isAdmin
			AND PermissionsManageCases = true
			ORDER BY CreatedDate ASC 
			LIMIT 1
		];

		User testUser = new User(
			Alias = 'newUser',
			Email='newuser@testorg.com',
			EmailEncodingKey='UTF-8',
			LastName='Testing',
			LanguageLocaleKey='en_US',
			LocaleSidKey='en_US',
			ProfileId = prof.Id,
			TimeZoneSidKey='America/Los_Angeles',
			UserName = String.valueOf(Crypto.getRandomInteger()) + 'myusername@testorg.com');

		return testUSer;
	}

	/*
	* @description
	*	Creates picklist values
	* @params
	*	None
	* @return
	*	None
	*/
	public static void insertPicklistValues() {
		// Insert test data
		List<Article_Feedback_Values__c> valuesToInsert = new List<Article_Feedback_Values__c>();
		
		valuesToInsert.add(createPicklistValue('value1', true, false, 1, 0));
		valuesToInsert.add(createPicklistValue('value2', false, true, 0, 1));
		valuesToInsert.add(createPicklistValue('value3', true, false, 0, 0));
		valuesToInsert.add(createPicklistValue('value4', false, true, 0, 0));

		INSERT valuesToInsert;
	}

	/*
	* @description
	*	Creates picklist values
	* @params
	*	String, Boolean, Boolean, Integer, Boolean
	* @return
	*	Article_Feedback_Values__c with value
	*/
	static Article_Feedback_Values__c createPicklistValue(String sValue, Boolean isPositive, Boolean isNegative, Integer orderPositive, Integer orderNegative) {
		Article_Feedback_Values__c result = new Article_Feedback_Values__c(
			Value__c = sValue, 
			Positive__c = isPositive, 
			Negative__c = isNegative,
			OrderPositive__c = orderPositive,
			OrderNegative__c = orderNegative
		);

		return result;
	}
}