src/objects/Article_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Article_Number__c</fullName>
        <label>Article Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Type__c</fullName>
        <label>Article Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Version__c</fullName>
        <label>Article Version</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Article_Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Name__c</fullName>
        <label>Community Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feedback_Source__c</fullName>
        <label>Feedback Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Communities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Feedback_Status__c</fullName>
        <label>Feedback Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Feedback__c</fullName>
        <label>Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Article Feedback</label>
    <nameField>
        <label>Article Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ArticleFeedbackRelatedCtrl.cls
/**
 * @author Altimetrik
 * @description
 *    started on 07/05/2018
 *    Retrieves article feedbacks related to current article feedback
 **/
public with sharing class ArticleFeedbackRelatedCtrl {

   public List<Article_Feedback__c> records {get; set;}

   public ArticleFeedbackRelatedCtrl(ApexPages.StandardController std) {
       Article_Feedback__c af = (Article_Feedback__c)std.getRecord();
       af = [select Article_Number__c, Article_Type__c, Article_Version__c from Article_Feedback__c where id =: af.Id limit 1];
       records = [select Id, Name, Feedback_Source__c, Feedback_Status__c, Assigned_To__c, Community_Name__c ,Feedback__c, CreatedDate
                  from Article_Feedback__c
                  where Article_Number__c =: af.Article_Number__c and
                       Article_Type__c =: af.Article_Type__c and
                       Article_Version__c =: af.Article_Version__c
                       and id !=: af.id
                       order by CreatedDate DESC
                       limit 1000];
   }
}