src/objects/Article_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Article_Feed_Update__c</fullName>
        <inlineHelpText>The contents of this field will appear in the Article feed internally AND in the Community if the Article is shared in a Community.</inlineHelpText>
        <label>Article Feed Update</label>
        <length>4500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Article_Number__c</fullName>
        <label>Article Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Title__c</fullName>
        <label>Article Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feedback_Status__c</fullName>
        <label>Feedback Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Internal_Notes__c</fullName>
        <label>Internal Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Parent_FeedItem__c</fullName>
        <label>Parent FeedItem</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Article Feedback</label>
    <nameField>
        <label>Article Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdatedArticleFeedback_Test.cls
/**
 * @author Altimetrik
 * @description
 *    started on 07/05/2018
 *    Test class for the UpdateArticleFeedback trigger
 **/

@isTest
private class UpdatedArticleFeedback_Test{

	static testMethod void testTrigger() {

        // creates dummy KnowledgeArticleVersion
        string publishStatus = 'draft';
        Map<String,Schema.SOBjectType> gd = Schema.getGlobalDescribe();

        List<String> kavNames = new List<String>();
        for (String s : gd.keySet()) {
          if (s.contains('__kav')) {
            kavNames.add(s);
          }
        }

        String default_language = [SELECT LanguageLocaleKey FROM Organization limit 1].LanguageLocaleKey;
        String objType = kavNames.get(0);
        SObject kavObj;
        kavObj = Schema.getGlobalDescribe().get(objType).newSObject();
        kavObj.put('Title','Foo Foo Foo!!!'+String.valueOf(Crypto.getRandomInteger()));
        kavObj.put('UrlName', 'foo-foo-foo'+String.valueOf(Crypto.getRandomInteger()));
        kavObj.put('Summary', 'This is a summary!!! Foo. Foo. Foo.');
        kavObj.put('Language', ArticleFeedbackSecurityHandler.getValidLanguagePicklistValue(objType));
        insert kavObj;

        // requery the kavObj to get the KnowledgeArticleId on it that is created automatically
        String q = 'select KnowledgeArticleId, Title from KnowledgeArticleVersion where Id = \'' +kavObj.get('Id')+  '\' and PublishStatus = :publishStatus';
        kavObj = (KnowledgeArticleVersion)Database.query(q);

        // creates dummy FeedItem
        FeedItem post = new FeedItem();
        post.Body = 'This is a test post';
        post.Type = 'TextPost';
        post.ParentId = (String)kavObj.get('KnowledgeArticleId');
        insert post;

		// creates dummy Article Feedback object
		Article_Feedback__c afeedback = new Article_Feedback__c();
        afeedback.Feedback_Status__c = 'New';
        afeedback.Article_Title__c = 'Test Article Title';
        afeedback.Article_Number__c = '00001';
        afeedback.Internal_Notes__c = 'Test notes';
        afeedback.Article_Feed_Update__c = '';
        afeedback.Parent_FeedItem__c = post.Id;
		insert afeedback;

    	System.Test.startTest();
        	afeedback.Article_Feed_Update__c = 'Test update';
            update afeedback;
            System.assertEquals (afeedback.Article_Feed_Update__c ,'Test update');
        System.Test.stopTest();
	}
}