src/objects/Article_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Action_Date__c</fullName>
        <label>Action Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Action_Taken__c</fullName>
        <label>Action Taken</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Article Archived</fullName>
                </value>
                <value>
                    <fullName>Article Updated</fullName>
                </value>
                <value>
                    <fullName>No Action Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Article_Created_Date__c</fullName>
        <label>Article Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Article_Feed_Update__c</fullName>
        <inlineHelpText>The contents of this field will appear in the Article feed internally AND in the Community if the Article is shared in a Community.</inlineHelpText>
        <label>Article Feed Update</label>
        <length>4500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Article_Link__c</fullName>
        <label>Article Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Article_Number__c</fullName>
        <label>Article Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Title__c</fullName>
        <label>Article Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Type__c</fullName>
        <label>Article Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Version__c</fullName>
        <label>Article Version</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Article_Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Name__c</fullName>
        <label>Community Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feedback_Source__c</fullName>
        <label>Feedback Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Communities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Feedback_Status__c</fullName>
        <label>Feedback Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Feedback__c</fullName>
        <label>Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Internal_Notes__c</fullName>
        <label>Internal Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Is_Current_User__c</fullName>
        <formula>Assigned_To__c = $User.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Current User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Published_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Published By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Article_Feedback_Published</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Published_Date__c</fullName>
        <label>Last Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Parent_FeedItem__c</fullName>
        <label>Parent FeedItem</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Article Feedback</label>
    <nameField>
        <label>Article Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/kfk_WrapperCtrl.cls
/**
 * @author Altimetrik
 * @description
 *  started on MM/DD/YYYY
 *  REPLACE_BY_CLASS_LOGIC_RESPONSABILITIES
 **/
public with sharing class kfk_WrapperCtrl {
    // Constants

    //************************************************************************
    // Properties & data members



    //************************************************************************
    // Methods

    public kfk_WrapperCtrl() {}


    @AuraEnabled
    public static kfk_LightningResponse getInitData(String recordId){

	    kfk_LightningResponse response = new kfk_LightningResponse();
       	Map<String,Object> result = new Map <String,Object>();
		//get Ka Id from Kav Id
		List<KnowledgeArticleVersion> kaList = [SELECT Id,KnowledgeArticleId 
                                                FROM KnowledgeArticleVersion where id =:recordId];
        if (!kaList.isEmpty()){
            KnowledgeArticleVersion k = kaList.get(0);
            Vote res;
            List<Vote> voteResult = [SELECT CreatedById,CreatedDate,Id,IsDeleted,LastModifiedById,
                              		LastModifiedDate,ParentId,SystemModstamp,Type 
                              	FROM Vote WHERE ParentId =: k.KnowledgeArticleId];
        	if (!voteResult.isEmpty())
                res  = voteResult.get(0);
        	result.put('ka_vote',res);
            
            Article_Feedback__c fRes;
            String kId = '%'+k.KnowledgeArticleId+'%';
            List<Article_Feedback__c> feedbackResult = [SELECT Action_Date__c,Action_Taken__c,Article_Created_Date__c,Article_Feed_Update__c,
                                     		Article_Link__c,Article_Number__c,Article_Title__c,Article_Type__c,Article_Version__c,
                                     		Assigned_To__c,Community_Name__c,CreatedById,CreatedDate,Feedback_Source__c,Feedback_Status__c,
                                     		Feedback__c,Id,Internal_Notes__c,IsDeleted,Is_Current_User__c,Language__c,
                                     	LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Last_Published_By__c,
                                     	Last_Published_Date__c,Name,OwnerId,Parent_FeedItem__c,SystemModstamp 
                                     		FROM Article_Feedback__c 
                                     WHERE Article_Link__c LIKE :kId AND CreatedById =:UserInfo.getUserId()];
            
            system.debug('\n k.KnowledgeArticleId :'+k.KnowledgeArticleId+'\n UserInfo.getUserId() :'+UserInfo.getUserId());
            if (!feedbackResult.isEmpty())
                fRes  = feedbackResult.get(0);
            result.put('ka_feedback',fRes);
        response.jsonResponse = JSON.serialize(result);
        }
        
		return response;
    }



    @AuraEnabled
    public static kfk_LightningResponse loadKAVId(String recordId){
        kfk_LightningResponse response = new kfk_LightningResponse();
        Map<String,  Object> result = new Map<String,  Object>();
        String kavId = '';
        try{
            response.state = 'SUCCESS';
            List<Article_Feedback__c > l = [Select Id, Article_Link__c  from Article_Feedback__c  where id=:recordId];

            if (!l.isEmpty()){
                String aux =  l.get(0).Article_Link__c;
                List<String> tmp = aux.split('/');
                kavId = tmp.get(tmp.size()-1);
                result.put('kavId', kavId);
                Boolean isArchived = false;
                string query =  '	SELECT Id,ArchivedDate, KnowledgeArticleId '+
                                '	FROM KnowledgeArticleVersion ' +
                                '	WHERE PublishStatus = \'Archived\' ' +
                                            ' and Id = \'' + kavId + '\' ';
                //aqi_SecurityHandler.canAccess(KnowledgeArticleVersion.sObjectType);
                List<KnowledgeArticleVersion> actualKavs =  Database.query(query);
                if(!actualKavs.isEmpty()){
                    isArchived = true;
                }
                result.put('isArchived', isArchived);
            }
            else {
                response.state = 'ERROR';
                response.error = 'An error occurred getting the id of the related article, please check that the component is in the correct record page.';
            }

            response.jsonResponse = JSON.serialize(result);

        }
        catch(Exception e){
            response.state = 'ERROR';
        }
system.debug('\n======\n');
        
system.debug(response);

        return response;
    }

}