src/objects/Knowledge_feedback__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for Knowledge Feedback Tracking</description>
    <fields>
        <fullName>Hashtag__c</fullName>
        <defaultValue>&quot;#ArticleFeedback&quot;</defaultValue>
        <description>Hashtag is used to create an Article Feedback object when it is present in a Chatter feed for an Article.</description>
        <inlineHelpText>Type prefixed with the hash character (#).</inlineHelpText>
        <label>Hashtag</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Knowledge feedback</label>
</CustomObject>

src/classes/ArticleFeedbackConfigCtrl_Test.cls
/**
 * @author Altimetrik
 * @description
 *    started on 07/12/2018
 *    Test class for the ArticleFeedbackConfigCtrl class
 **/
@isTest
public class ArticleFeedbackConfigCtrl_Test {

	static testMethod void test_config() {
        Knowledge_Feedback__c setting = new Knowledge_Feedback__c();
        setting.Hashtag__c = '#TestHashtag';
        insert setting;

        System.Test.startTest();
            System.assertNotEquals(null,setting);
            ArticleFeedbackConfigCtrl ctr = new ArticleFeedbackConfigCtrl();
            ctr.edit();
            ctr.csObj.HashTag__c ='#MyTestHashtag';
            ctr.save();
            setting = Knowledge_Feedback__c.getOrgDefaults();
            system.assertEquals('#MyTestHashtag',setting.Hashtag__c);
            ctr.cancel();
        System.Test.stopTest();
    }
}